#ダメージ取得用
#シベリアのプラグインが前提

on damage of player:
	#set {_attacker} to expand attacker
	if final damage is not damage:
		broadcast "&c[Damage]&3«%final damage * 2%»&f--->> &c&l†&f&l%victim%&c&l† &6%final damage / damage * 100%％"
		#broadcast "&c[Armor]&b%damage * 2%&3==>>&b%final damage * 2% &3%final damage / damage * 100%％"
	else:
		broadcast "&c[Damage]&3«%damage * 2%»&f--->> &c&l†&f&l%victim%&c&l†"