on script load:
	wait 60 seconds
	execute console command "sk reload /SAGASA/FlansAliases"

command /iniplugin:
	permission: console.console
	trigger:
		send "&cプレイヤーデータを削除すること！！！！！！！！！"
		execute console command "/adminkillreward clear"
		execute console command "/adminresearchgui clear"
		execute console command "/MineLimitReset"
		execute console command "/economy resetall"
		execute console command "/ItemCompression clear"