on damage:
	if attacker is player:
		if attacker is holding wood sword:
			set damage to 1.5
		if attacker is holding gold sword:
			set damage to 1.5
		if attacker is holding stone sword:
			set damage to 2
		if attacker is holding iron sword:
			set damage to 2
		if attacker is holding diamond sword:
			set damage to 2.5
		if attacker is holding pick:
			set damage to 1
		if attacker is holding axe:
			set damage to 1.5
		if attacker is holding shovel:
			set damage to 1