on death of player:
	heal victim
	execute console command "gamemode 1 %victim%"
	set {dt.%victim%} to true
	apply invisibility 1 to victim for 5 second
	wait 5 seconds
	clear victim's inventory
	execute console command "gamemode 0 %victim%"
	teleport victim to location (0 , 250 , 720) in world "world"
	clear {dt.%victim%}
	
on damage:
	if {dt.%attacker%} is set:
		cancel event
		
on break:
	if {dt.%player%} is set:
		cancel event